name = "nomads"
version = 67
copyright = "brute51"
description = "adds a new faction to the game"
author = "CookieNoob, Exotic_Retard, Brute51, original nomads team"
uid = "50423624-1e83-4fc2-85b3-nomadsv00067"
url = ""
icon = ""
identifier = ""
selectable = false
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
