ainames = table.merged( ainames, {
    nomads = {    -- Nomads AI player names
        'Admiral Vantoga',
        'Ara Aidt',
        'Atet Tonet',
        'Bananana',
        'Benzai',
        'Bladal',
        'Burvor',
        'Colin Liedtke',
        'Dalton Lasalle',
        'Diamand',
        'Elinor Markell',
        'Elliot Jorden',
        'Elmrade',
        'Freddy Quick',
        'Gonzalo Guetersloh',
        'Guillermina Bouton',
        'Heriberto Zinda',
        'Issrak',
        'Keil Thorman',
        'Lucinda Robichau',
        'Merlin',
        'Omar Abdou',
        'Paul Artreides',
        'Ramiro Ganska',
        'Randell Strawhorn',
        'Rothlernys',
        'Rupert',
        'Sarahogi',
        'Saratoga',
        'Sir Killalot',
        'Suzette Nylen',
        'Tako Karides',
        'Tintassam Sulan',
        'Torkach',
        'Zuper',

        -- names of Nomads team members that wanted to be in this list (the name might be slightly altered)
        'Brute',
        'Kirvesnaama',
        'Scalestor',
        'Domino',
        'MushrooMars',
        'jgaltrearden',
        'Pip',
        'Moritz',
        'Dilli',
        'ColonelSheppard',
        'Intekin',

        -- old team
        'Colonel Jessep',
        'ZombieJesus',
        'Legion Darrath',
        'Pureon',
        'FightFear',
        
        -- new team
        'CookieNoob',
        'Exotic_Retard',
        'KeyBlue',
        'Ithilis',
        'RK4000',
        'JJs_AI',
    },
} )
