layout = {
    ['acu_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['acu_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['acu_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['acu_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },
    ['dsu_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['dsu_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['dsu_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['dsu_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },
    ['red_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['red_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['red_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['red_btn_up'] = {left = 1, top = 0, width = 63, height = 64, },
    ['led_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['led_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['led_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['led_btn_up'] = {left = 1, top = 0, width = 63, height = 64, },
    ['ed_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['ed_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['ed_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['ed_btn_up'] = {left = 1, top = 0, width = 63, height = 64, },
    ['hamc_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['hamc_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['hamc_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['hamc_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },
    ['heo_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['heo_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['heo_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['heo_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },
    ['psg_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['psg_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['psg_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['psg_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },
    ['pqt_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['pqt_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['pqt_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['pqt_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },
    ['rj_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['rj_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['rj_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['rj_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },
    ['sre_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['sre_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['sre_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['sre_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },
    ['isb_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['isb_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['isb_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['isb_btn_up'] = {left = 1, top = 0, width = 63, height = 64, },
    ['sgf_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['sgf_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['sgf_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['sgf_btn_up'] = {left = 1, top = 0, width = 63, height = 64, },
    ['ees_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['ees_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['ees_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['ees_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },
    ['aes_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['aes_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['aes_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['aes_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },
    ['strn_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['strn_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['srtn_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['srtn_btn_up'] = {left = 1, top = 0, width = 63, height = 64, },
    ['tm_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['tm_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['tm_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['tm_btn_up'] = {left = 1, top = 0, width = 63, height = 64, },

    ['df_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['df_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['df_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['df_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },

    ['mlg_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['mlg_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['mlg_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['mlg_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },
    ['mlg2_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['mlg2_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['mlg2_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['mlg2_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },

    ['fltr_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['fltr_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['fltr_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['fltr_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },

    ['srs_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['srs_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['srs_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['srs_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },

    ['ses_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['ses_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['ses_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['ses_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },

    ['sre_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['sre_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['sre_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['sre_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },

    ['hamc2_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['hamc2_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['hamc2_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['hamc2_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },

    ['pa_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['pa_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['pa_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['pa_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },

    ['sm_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['sm_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['sm_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['sm_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },

    ['il_btn_sel'] = {left = 1, top = 0, width = 63, height = 64, },
    ['il_btn_down'] = {left = 2, top = 2, width = 60, height = 60, },
    ['il_btn_over'] = {left = 2, top = 2, width = 60, height = 60, },
    ['il_btn_up'] = {left = 2, top = 2, width = 60, height = 60, },

}
