name = "Nomads Test - SCU factory enhanced"
uid = "58091ca6-9f27-4e77-aafc-1fb8f6a5ab1e"
version = 1
copyright = ""
description = "Adds factory enhanced SCUs to all other factions (besides Nomads)"
author = "Nomads Team"
icon = "/textures/mods/nomadslogo_testmod.dds"
url = ""
selectable = false
enabled = false
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = {}
before = { }
after = { }
